# Generated by Django 3.0.5 on 2020-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200408_1757'),
        ('carts', '0006_auto_20200409_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='web.Product'),
        ),
    ]
