# Generated by Django 3.0.5 on 2020-12-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20200410_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery',
            field=models.CharField(choices=[('SELF_PICKUP', 'Self pickup'), ('DELIVERY_CHOISE', 'Delivery DHL or DPD')], default='DELIVERY_CHOISE', max_length=100, verbose_name='Доставка'),
        ),
    ]
