# Generated by Django 3.0.5 on 2020-12-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_cartitem_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery',
        ),
    ]
