# Generated by Django 3.0.5 on 2020-04-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('availability', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('force', 'force'), ('pompe', 'pompe')], default='force', max_length=20)),
                ('url', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(default='pictures/product_image/noimage.png', upload_to='pictures/product_image')),
            ],
        ),
    ]
