# Generated by Django 3.0.5 on 2020-04-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
