# Generated by Django 3.0.5 on 2020-04-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200407_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='active',
        ),
    ]
