# Generated by Django 3.0.5 on 2020-04-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200408_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'url')},
        ),
    ]
