# Generated by Django 3.0.5 on 2020-04-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200408_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('number', 'slug')},
        ),
    ]
