# Generated by Django 3.0.5 on 2020-04-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200414_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
