# Generated by Django 3.0.5 on 2020-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
