# Generated by Django 3.0.5 on 2020-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
    ]
