# Generated by Django 3.0.5 on 2020-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
