# Generated by Django 3.0.5 on 2020-12-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201206_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('self', 'self delivery'), ('dhl or dpd', 'dhl or dpd')], max_length=100),
        ),
    ]
